# 应用服务 WEB 访问端口
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Asdf1234
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=huochai

# ?? Tomcat ? SSL ???
server.tomcat.redirect-context-root=true
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for


server.http.port=8080