# 应用服务 WEB 访问端口
server.port=8443
server.ssl.key-store=/Users/huochai/IdeaProjects/huochai/keystore.p12
server.ssl.key-store-password=Asdf1234
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=huochai