# Resource Server Port
server.port=8081

# Application Name
spring.application.name=resource-server

# OAuth2 Resource Server JWT Issuer URI
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000

# Logging
logging.level.org.springframework.security=DEBUG